### ISSUE TITLE
Mock patients - info

### ISSUE THREAD

**Issue by matijagrcic** [StanfordBDHG/LLMonFHIR#51] opened 2024-09-18 14:20 UTC
### Description

I'm interested in why the mock patient data was removed and only the .json.license files are left.

Added:
https://github.com/StanfordBDHG/LLMonFHIR/pull/38/files

Removed:
https://github.com/StanfordBDHG/LLMonFHIR/pull/42/files

Current:
https://github.com/StanfordBDHG/LLMonFHIR/tree/main/LLMonFHIR/Resources/Mock%20Patients

### Reproduction

N/A

### Expected behavior

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment] 2024-09-18 16:49
Duplicate of #50

**Closed by PSchmiedmayer** 2024-09-18 16:49 UTC
Labels: bug

**Comment by matijagrcic** [comment] 2024-09-19 08:26
Thanks @PSchmiedmayer i've missed that, seems that it's not rendered on the readme.md

![image](https://github.com/user-attachments/assets/54af2405-1c66-41ec-9403-f11ffec6b524)

![image](https://github.com/user-attachments/assets/91bb7ac8-3886-4adb-af72-b39cfe27c4b4)
